language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -t mangilal23/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true mangilal23/docker-react npm run test
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "deer"
    env: "Deer-env"
    bucket_name: "elasticbeanstalk-us-east-2-491320997429"
    bucket_path: "deer"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY